[info]
name = "backup"
desc = "Backup and restore utilities"

[script.install-tools]
desc = "Install backup tools"
sudo = true
commands = [
    "apt update",
    "apt install -y rsync tar gzip",
    "apt install -y rclone",
    "rsync --version",
    "tar --version"
]

[script.create-backup-dir]
desc = "Create backup directory structure"
sudo = true
commands = [
    "mkdir -p /opt/backups/{daily,weekly,monthly}",
    "mkdir -p /opt/backups/logs",
    "chmod 700 /opt/backups",
    "ls -la /opt/backups/"
]

[script.backup-home]
desc = "Backup home directories"
sudo = true
commands = [
    "tar -czf /opt/backups/daily/home_backup_$(date +%Y%m%d_%H%M%S).tar.gz /home",
    "ls -la /opt/backups/daily/"
]

[script.backup-etc]
desc = "Backup system configuration"
sudo = true
commands = [
    "tar -czf /opt/backups/daily/etc_backup_$(date +%Y%m%d_%H%M%S).tar.gz /etc",
    "ls -la /opt/backups/daily/"
]

[script.backup-var]
desc = "Backup /var directory (excluding logs)"
sudo = true
commands = [
    "tar -czf /opt/backups/daily/var_backup_$(date +%Y%m%d_%H%M%S).tar.gz --exclude=/var/log --exclude=/var/cache /var",
    "ls -la /opt/backups/daily/"
]

[script.cleanup-old]
desc = "Cleanup old backups (older than 30 days)"
sudo = true
commands = [
    "find /opt/backups/daily -name '*.tar.gz' -mtime +30 -delete",
    "find /opt/backups/weekly -name '*.tar.gz' -mtime +90 -delete",
    "find /opt/backups/monthly -name '*.tar.gz' -mtime +365 -delete",
    "echo 'Old backups cleaned up'"
]

[script.restore-test]
desc = "Test backup restoration"
sudo = false
commands = [
    "echo 'To restore a backup, use:'",
    "echo 'tar -xzf /opt/backups/daily/backup_file.tar.gz -C /'",
    "echo 'Available backups:'",
    "ls -la /opt/backups/daily/ || echo 'No backups found'"
]