[info]
name = "redis"
desc = "Redis in-memory data store setup"

[script.install]
desc = "Install Redis server"
sudo = true
commands = [
    "apt update",
    "apt install -y redis-server",
    "systemctl enable redis-server",
    "systemctl start redis-server",
    "redis-cli ping"
]

[script.configure]
desc = "Configure Redis for production"
sudo = true
commands = [
    "cp /etc/redis/redis.conf /etc/redis/redis.conf.backup",
    "sed -i 's/# maxmemory <bytes>/maxmemory 256mb/' /etc/redis/redis.conf",
    "sed -i 's/# maxmemory-policy noeviction/maxmemory-policy allkeys-lru/' /etc/redis/redis.conf",
    "sed -i 's/bind 127.0.0.1 ::1/bind 127.0.0.1/' /etc/redis/redis.conf",
    "systemctl restart redis-server"
]

[script.secure]
desc = "Secure Redis with password"
sudo = true
commands = [
    "echo 'requirepass your_strong_password_here' >> /etc/redis/redis.conf",
    "systemctl restart redis-server",
    "echo 'Redis secured with password. Update your applications accordingly.'"
]

[script.test]
desc = "Test Redis functionality"
sudo = false
commands = [
    "redis-cli set test_key 'Hello Redis'",
    "redis-cli get test_key",
    "redis-cli del test_key",
    "redis-cli info memory"
]

[script.monitor]
desc = "Monitor Redis performance"
sudo = false
commands = [
    "redis-cli info stats",
    "redis-cli info memory",
    "redis-cli info clients",
    "redis-cli slowlog get 10"
]

[script.uninstall]
desc = "Uninstall Redis completely"
sudo = true
commands = [
    "systemctl stop redis-server",
    "systemctl disable redis-server",
    "apt remove -y redis-server",
    "apt autoremove -y",
    "rm -rf /var/lib/redis",
    "rm -rf /etc/redis"
]