[info]
name = "docker"
description = "Container platform"

[service]
start = true
enable = true

[check]
command = "which docker"

[install]
type = "command"
commands = [
    "apt remove -y docker.io docker-doc docker-compose podman-docker containerd runc || true",
    "apt-get install -y ca-certificates curl",
    "install -m 0755 -d /etc/apt/keyrings",
    "curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc",
    "chmod a+r /etc/apt/keyrings/docker.asc",
    """\
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list \
    """,
    "apt update",
    "apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin",
    "which docker"
]

[uninstall]
type = "command"
commands = [
    "apt-get purge -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras || true",
    "apt-get autoremove -y",
    "rm -rf /var/lib/docker",
    "rm -rf /var/lib/containerd",
    "rm -rf /etc/docker",
    "rm -f /etc/apt/sources.list.d/docker.list",
    "rm -f /etc/apt/keyrings/docker.asc"
]
